name: Build Windows Releases

on:
  push:
    branches:
      - master
      - actions
    tags:
      - '*'

jobs:
  get_version_name:
    name: Get version name
    runs-on: ubuntu-latest
    outputs:
      rev_count: ${{ steps.rev.outputs.REVCOUNT }}
      version_name: ${{ steps.rev.outputs.VERSION_NAME }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set version name
      id: rev
      run: |
        cd ${{ github.workspace }}
        REVCOUNT=`git rev-list --count HEAD`
        echo "rev_count=${REVCOUNT}" >> $GITHUB_OUTPUT
        if [[ "${{ github.ref }}" =~ "refs/tags/" ]]; then
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
        else
          VERSION=r${REVCOUNT}
        fi
        echo "version_name=${VERSION}" >> $GITHUB_OUTPUT

  build:
    name: Upload Release Asset
    runs-on: windows-2022
    needs: get_version_name

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86

      - name: MSBuild
        run: |
          msbuild bandingMT_simd.sln /t:build /p:configuration=Release /p:Platform=Win32 -maxcpucount

      - name: Create Archieve
        id: archieve
        run: |
          mkdir bandingMT_simd_release
          copy Win32\Release\bandingMT_simd.auf bandingMT_simd_release
          copy bandingMT_simd_readme.txt bandingMT_simd_release
          7z a -mx9 bandingMT_simd_${{ needs.get_version_name.outputs.version_name }}.zip .\bandingMT_simd_release\*

      - name: Calc hash
        id: calc_hash
        run: |
          7z h -scrc* .\bandingMT_simd_${{ needs.get_version_name.outputs.version_name }}.zip

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: .\bandingMT_simd_${{ needs.get_version_name.outputs.version_name }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandingMT_simd_${{ needs.get_version_name.outputs.version_name }}
          path: bandingMT_simd_${{ needs.get_version_name.outputs.version_name }}.zip